"""Vulnerability rules: sinks, secure-alternatives, and AST analysis logic."""
from .models import Rule

RULES = [
    Rule(name="OS Command Injection", cwe="CWE-78", severity="CRITICAL",
         description="Unsanitized user input reaches a shell / subprocess call.",
         remediation="Use subprocess.run(..., shell=False) with an argument list and never concatenate user input into a command string.",
         languages=["python", "javascript", "php", "ruby", "go", "java", "c", "cpp", "csharp", "shell"]),
    Rule(name="Code Injection (eval/exec)", cwe="CWE-94", severity="CRITICAL",
         description="Dynamic execution of attacker-controlled strings (eval/exec).",
         remediation="Never eval/exec user input. Refactor to safe data structures.",
         languages=["python", "javascript", "php", "ruby"]),
    Rule(name="SQL Injection", cwe="CWE-89", severity="CRITICAL",
         description="SQL built by string concatenation / interpolation of untrusted input.",
         remediation="Use parameterized queries / prepared statements (?, %s placeholders).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Insecure Cryptography", cwe="CWE-327", severity="HIGH",
         description="Use of cryptographically broken hashing / cipher (MD5, SHA1, DES, RC4).",
         remediation="Use SHA-256+ / bcrypt / Argon2 for hashing; AES-GCM for encryption.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Cross-Site Scripting (XSS)", cwe="CWE-79", severity="HIGH",
         description="User input written unsanitized into HTML/JS output.",
         remediation="HTML-encode output; use a templating engine with auto-escaping.",
         languages=["javascript", "typescript", "php", "python", "ruby"]),
    Rule(name="Path Traversal", cwe="CWE-22", severity="HIGH",
         description="User input used to build a filesystem path without validation.",
         remediation="Canonicalize and validate paths against an allow-list root directory.",
         languages=["python", "javascript", "php", "ruby", "java", "go", "c"]),
    Rule(name="Hardcoded Credential", cwe="CWE-798", severity="HIGH",
         description="Hardcoded password, API key, or secret token in source.",
         remediation="Move secrets to environment variables or a secrets manager (e.g. vault).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Insecure Deserialization", cwe="CWE-502", severity="CRITICAL",
         description="Deserializing untrusted data (pickle, unserialize, Marshal.load).",
         remediation="Only deserialize from trusted sources; prefer safe formats (JSON).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Server-Side Template Injection", cwe="CWE-1336", severity="CRITICAL",
         description="User input reaches a server-side templating engine.",
         remediation="Pass data (not template strings) into the engine; sandbox the renderer.",
         languages=["python", "javascript", "typescript", "php", "ruby", "go", "java"]),
    Rule(name="Server-Side Request Forgery", cwe="CWE-918", severity="HIGH",
         description="Server fetches a user-controlled URL.",
         remediation="Validate and allow-list outbound URLs; block private/link-local ranges.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="XML External Entity (XXE)", cwe="CWE-611", severity="HIGH",
         description="XML parser that resolves external entities.",
         remediation="Disable DTD/external entity resolution in the XML parser.",
         languages=["python", "java", "php", "csharp"]),
    Rule(name="LDAP Injection", cwe="CWE-90", severity="HIGH",
         description="Unsanitized input flows into an LDAP search filter.",
         remediation="Escape LDAP metacharacters and use parameterized search APIs.",
         languages=["python", "java", "php", "csharp"]),
    Rule(name="Insecure JWT", cwe="CWE-347", severity="HIGH",
         description="JWT with 'none' algorithm or disabled signature verification.",
         remediation="Require a strong signing algorithm and verify signatures explicitly.",
         languages=["python", "javascript", "typescript", "go", "java"]),
    Rule(name="Insecure Randomness", cwe="CWE-330", severity="MEDIUM",
         description="Non-cryptographic random used for security-sensitive value.",
         remediation="Use a CSPRNG (secrets module, crypto.randomBytes, SecureRandom).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go"]),
    Rule(name="Open Redirect", cwe="CWE-601", severity="MEDIUM",
         description="Redirect target derived from user input without validation.",
         remediation="Validate redirect URLs against an allow-list; reject absolute/opaque URLs.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go"]),
    Rule(name="Log Injection", cwe="CWE-117", severity="MEDIUM",
         description="Unsanitized user input written to logs (log forging).",
         remediation="Sanitize/disallow newlines in logged values.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go"]),
    Rule(name="Insecure YAML Deserialization", cwe="CWE-502", severity="CRITICAL",
         description="Unsafe YAML load of untrusted data.",
         remediation="Use a safe loader (yaml.safe_load) or a JSON-based format.",
         languages=["python", "ruby", "go", "java"]),
]

SINKS = {
    "python": [
        r"\bos\.system\s*\(", r"\bos\.popen\s*\(", r"\bsubprocess\.(call|Popen|run|check_output|check_call)\s*\(",
        r"\beval\s*\(", r"\bexec\s*\(", r"\bpickle\.loads?\s*\(", r"\byaml\.load\s*\(",
        r"\.execute\(\s*.*%|f\"[\s\S]*?%|\.format\([\s\S]*?%",
        r"\bcrypt\b[^\n]*(md5|sha1|des|rc4)|md5\s*\(|sha1\s*\(",
        r"\bhashlib\.(md5|sha1)\s*\(", r"MD5\s*\(", r"Crypto\.Hash\.(MD5|SHA1|MD4)",
        r"\bopen\s*\([^)]*['\"][a-z]:?/|send_file\s*\([^)]*request",
        r"random\.randint|random\.random\s*\(\)",
        r"cryptography[^\n]*(DES|RC4|Blowfish)",
        r"requests\.(get|post)\s*\([^)]*(request|input|url|args)",
        r"etree\.parse\s*\(|fromstring\s*\(|lxml\.etree|xml\.etree|minidom\.parse|sax\.parse",
        r"jinja2\.Template\s*\(|render_template_string\s*\(|\.from_string\s*\(",
        r"ldap\.|ldap3\.|search_s\s*\(|\bLDAPSearch\b",
        r"redirect\s*\([^)]*(request|input|url|next|args)|HttpResponseRedirect\s*\([^)]*(request|input)",
        r"jwt\.encode\s*\(|\"alg\"\s*:\s*[\"']none|verify_signature\s*=\s*False",
        r"logging\.\w+\s*\([^)]*(request|input|user|args|%|format)|logger\.\w+\s*\([^)]*(request|input)",
    ],
    "javascript": [
        r"\beval\s*\(", r"\bFunction\s*\(",
        r"(?:require\s*\(\s*['\"]child_process['\"]\s*\)\s*\.\s*)?\bexec(?:Sync)?\s*\(",
        r"\bspawn(?:Sync)?\s*\(", r"\bfork\s*\(",
        r"\.query\s*\(\s*['\"][\s\S]*\+|`SELECT[\s\S]*\$\{",
        r"document\.write\s*\(|\.innerHTML\s*=|dangerouslySetInnerHTML|insertAdjacentHTML",
        r"crypto\.createHash\s*\(\s*['\"]md5|crypto\.createHash\s*\(\s*['\"]sha1|MD5\s*\(",
        r"Math\.random\s*\(\)",
        r"readFile\s*\([^)]*req|sendFile\s*\([^)]*req",
        r"password\s*[:=]\s*['\"][^'\"]{4,}['\"]|api[_-]?key\s*[:=]\s*['\"]|secret\s*[:=]\s*['\"]|token\s*[:=]\s*['\"][A-Za-z0-9]{8,}",
        r"axios\.(get|post)\s*\([^)]*(req|url|input|location)|fetch\s*\([^)]*(req|url|input|location)",
        r"res\.redirect\s*\([^)]*(req|query|input|url)|location\.href\s*=|window\.location\s*=[^;]*(req|query|input)",
        r"jwt\.sign\s*\(|algorithm\s*:\s*['\"]none|jsonwebtoken[^\n]*none",
        r"console\.(log|error|warn)\s*\([^)]*(req\.|query\.|body\.|params)",
        r"ejs\.render\s*\(|\.render\s*\([^)]*(req|query|input)[^)]*\}|\{\{[\s\S]*\}\}[\s\S]*(req|query)",
    ],
    "typescript": [
        r"\beval\s*\(",
        r"(?:require\s*\(\s*['\"]child_process['\"]\s*\)\s*\.\s*)?\bexec(?:Sync)?\s*\(",
        r"\bspawn(?:Sync)?\s*\(", r"\.query\s*\(\s*['\"][\s\S]*\+",
        r"document\.write\s*\(|\.innerHTML\s*=|dangerouslySetInnerHTML",
        r"crypto\.createHash\s*\(\s*['\"]md5|crypto\.createHash\s*\(\s*['\"]sha1",
        r"Math\.random\s*\(\)",
        r"password\s*[:=]\s*['\"][^'\"]{4,}['\"]|api[_-]?key\s*[:=]\s*['\"]|secret\s*[:=]\s*['\"]",
        r"readFileSync\s*\([^)]*req|readFile\s*\([^)]*req",
        r"axios\.(get|post)\s*\([^)]*(req|url|input)|fetch\s*\([^)]*(req|url|input)",
        r"res\.redirect\s*\([^)]*(req|query|input)|location\.href\s*=",
        r"jwt\.sign\s*\(|algorithm\s*:\s*['\"]none",
        r"console\.(log|error|warn)\s*\([^)]*(req\.|query\.|body\.|params)",
    ],
    "php": [
        r"\b(eval|assert|system|exec|shell_exec|passthru|proc_open|popen)\s*\(",
        r"\$_(GET|POST|REQUEST|COOKIE)\s*\[",
        r"mysql_query\s*\(|mysqli_query\s*\([^)]*\$",
        r"md5\s*\(|sha1\s*\(|crypt\s*\(",
        r"echo\s+\$_(GET|POST|REQUEST)|print\s+\$_(GET|POST)",
        r"unserialize\s*\(|base64_decode\s*\([^)]*\$",
        r"password\s*=\s*['\"]|api_key\s*=\s*['\"]|secret\s*=\s*['\"]",
        r"header\s*\(\s*['\"]Location\s*:\s*\$_(GET|REQUEST)",
        r"fopen\s*\([^)]*\$_(GET|POST|REQUEST)|include\s*\([^)]*\$",
        r"new\s+DOMDocument|simplexml_load\s|xml_parse\s*\(|loadXML\s*\(",
    ],
    "ruby": [
        r"\b(system|exec|spawn|eval|%x|`)\b",
        r"params\[|params\\.", r"cookies\[|cookies\\.",
        r"ActiveRecord.*\#\{|where\s*\(.*\#\{|execute\s*\([^)]*\#\{",
        r"OpenSSL::Digest::(MD5|SHA1)|Digest::MD5|Digest::SHA1",
        r"respond_to.*params|render\s+inline\s*:.*params",
        r"redirect_to\s+params|redirect_to\s*\[.*params",
        r"Marshal\.load\s*|YAML\.load\s*",
        r"File\.read\s*\([^)]*params|send_file\s+params",
        r"password\s*=\s*['\"]|api_key\s*=\s*['\"]|secret\s*=\s*['\"]",
    ],
    "java": [
        r"Runtime\.getRuntime\(\)\.exec\s*\(|ProcessBuilder\s*\(",
        r"request\.getParameter\s*\(|request\.getHeader\s*\(",
        r"Statement\s+", r"executeQuery\s*\([^)]*\+|createStatement\s*\(",
        r"MessageDigest\.getInstance\s*\(\s*['\"]MD5|MessageDigest\.getInstance\s*\(\s*['\"]SHA-1",
        r"response\.getWriter\(\)\.print\s*\([^)]*request",
        r"new\s+ObjectInputStream\s*\(|readObject\s*\(",
        r"Password\s*=\s*['\"]|secret\s*=\s*['\"]|apiKey\s*=\s*['\"]",
        r"DocumentBuilderFactory|SAXParserFactory|XMLReader",
        r"jwt\.sign|sendRedirect\s*\([^)]*request",
    ],
    "go": [
        r"exec\.Command\s*\(|os\.StartProcess\s*\(",
        r"r\.URL\.Query\(\)|r\.FormValue\s*\(|c\.Query\s*\(|c\.Param\s*\(",
        r"db\.Query\s*\([^)]*\+|db\.Exec\s*\([^)]*\+",
        r"md5\.New\s*\(|sha1\.New\s*\(|md5\.Sum\s*\(",
        r"fmt\.Fprintf\s*\([^)]*w\s*,[^)]*r\.", r"template\.New\s*\([^)]*\|\{\{",
        r"http\.Redirect\s*\([^)]*r\.|os\.Args\b|os\.Getenv\b",
        r"json\.Unmarshal\s*\([^)]*r\.Body",
        r"Password\s*[:=]\s*['\"]|Secret\s*[:=]\s*['\"]|ApiKey\s*[:=]\s*['\"]",
    ],
    "c": [
        r"\bsystem\s*\(|\bpopen\s*\(|\bexeclp?\s*\(|\bexecv\w*\s*\(",
        r"\bgets\s*\(|\bscanf\s*\(|\bfgets\s*\(",
        r"strlen\s*\([^)]*\+.*sprintf|sprintf\s*\([^)]*%s[^)]*argv",
        r"MD5_Init|SHA1_Init",
        r"strcpy\s*\([^)]*argv|strcat\s*\([^)]*argv|memcpy\s*\([^)]*argv",
        r"password\s*=\s*['\"]|secret\s*=\s*['\"]",
    ],
    "cpp": [
        r"std::system\s*\(|system\s*\(|popen\s*\(",
        r"std::cin\s*>>|std::getline\s*\(",
        r"MD5\s*\(|SHA1\s*\(",
        r"strcpy\s*\([^)]*argv|strcat\s*\([^)]*argv",
        r"password\s*=\s*['\"]|secret\s*=\s*['\"]",
    ],
    "csharp": [
        r"Process\.Start\s*\(|UseShellExecute",
        r"Request\.QueryString\b|Request\.Form\b|Console\.ReadLine\s*\(",
        r"SqlCommand\s*\(|new\s+SqlCommand\s*\([^)]*\+",
        r"MD5\.Create\s*\(|SHA1\.Create\s*\(",
        r"Response\.Write\s*\([^)]*Request|Html\.Raw\s*\(",
        r"JsonSerializer|BinaryFormatter|Deserialize\s*\(",
        r"Password\s*=\s*['\"]|apikey\s*=\s*['\"]|secret\s*=\s*['\"]",
        r"Response\.Redirect\s*\([^)]*Request",
        r"XmlDocument|XDocument\.Load|XmlReader\s*\(",
    ],
    "shell": [
        r"\b(eval|exec)\s+", r"\bcurl\s+[^\n]*\$\{", r"\bwget\s+[^\n]*\$\{",
        r"rm\s+-rf\s+/|rm\s+-rf\s+\$\{",
        r"password\s*=\s*['\"]|api_key\s*=\s*['\"]|secret\s*=\s*['\"]|token\s*=\s*['\"]",
        r"\bcat\s+[^\n]*\$\{|bash\s+-c\s+[^\n]*\$\{",
    ],
}

SANITIZERS = {
    "python": [
        r"yaml\.safe_load\s*\(", r"html\.escape\s*\(",
        r"subprocess\.run\s*\(\s*\[[^]]*\]\s*,\s*shell\s*=\s*False",
        r"parameterized|\?\s*,\s*\[|\?\s*,\s*\(|execute\s*\([^)]*,\s*\[",
        r"secrets\.token|os\.urandom|random\.SystemRandom",
        r"hashlib\.sha256|hashlib\.sha3|bcrypt|argon2|pbkdf2",
    ],
    "javascript": [
        r"escapeHtml|\$\<|textContent|innerText|encodeURIComponent",
        r"parameterized|\?\s*,\s*\[|prepared\s*statement",
        r"crypto\.randomBytes|randomUUID|sha256",
    ],
    "typescript": [
        r"escapeHtml|textContent|innerText|encodeURIComponent",
        r"parameterized|\?\s*,\s*\[|prepared\s*statement",
        r"crypto\.randomBytes|sha256",
    ],
    "php": [
        r"htmlspecialchars\s*\(|escape\s*\(