"""Vulnerability rules: sinks, secure-alternatives, and AST analysis logic."""
from .models import Rule

RULES = [
    Rule(name="OS Command Injection", cwe="CWE-78", severity="CRITICAL",
         description="Unsanitized user input reaches a shell / subprocess call.",
         remediation="Use subprocess.run(..., shell=False) with an argument list and never concatenate user input into a command string.",
         languages=["python", "javascript", "php", "ruby", "go", "java", "c", "cpp", "csharp", "shell"]),
    Rule(name="Code Injection (eval/exec)", cwe="CWE-94", severity="CRITICAL",
         description="Dynamic execution of attacker-controlled strings (eval/exec).",
         remediation="Never eval/exec user input. Refactor to safe data structures.",
         languages=["python", "javascript", "php", "ruby"]),
    Rule(name="SQL Injection", cwe="CWE-89", severity="CRITICAL",
         description="SQL built by string concatenation / interpolation of untrusted input.",
         remediation="Use parameterized queries / prepared statements (?, %s placeholders).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Insecure Cryptography", cwe="CWE-327", severity="HIGH",
         description="Use of cryptographically broken hashing / cipher (MD5, SHA1, DES, RC4).",
         remediation="Use SHA-256+ / bcrypt / Argon2 for hashing; AES-GCM for encryption.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Cross-Site Scripting (XSS)", cwe="CWE-79", severity="HIGH",
         description="User input written unsanitized into HTML/JS output.",
         remediation="HTML-encode output; use a templating engine with auto-escaping.",
         languages=["javascript", "typescript", "php", "python", "ruby"]),
    Rule(name="Path Traversal", cwe="CWE-22", severity="HIGH",
         description="User input used to build a filesystem path without validation.",
         remediation="Canonicalize and validate paths against an allow-list root directory.",
         languages=["python", "javascript", "php", "ruby", "java", "go", "c"]),
    Rule(name="Hardcoded Credential", cwe="CWE-798", severity="HIGH",
         description="Hardcoded password, API key, or secret token in source.",
         remediation="Move secrets to environment variables or a secrets manager (e.g. vault).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Insecure Deserialization", cwe="CWE-502", severity="CRITICAL",
         description="Deserializing untrusted data (pickle, unserialize, Marshal.load).",
         remediation="Only deserialize from trusted sources; prefer safe formats (JSON).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="Server-Side Template Injection", cwe="CWE-1336", severity="CRITICAL",
         description="User input reaches a server-side templating engine.",
         remediation="Pass data (not template strings) into the engine; sandbox the renderer.",
         languages=["python", "javascript", "typescript", "php", "ruby", "go", "java"]),
    Rule(name="Server-Side Request Forgery", cwe="CWE-918", severity="HIGH",
         description="Server fetches a user-controlled URL.",
         remediation="Validate and allow-list outbound URLs; block private/link-local ranges.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go", "csharp"]),
    Rule(name="XML External Entity (XXE)", cwe="CWE-611", severity="HIGH",
         description="XML parser that resolves external entities.",
         remediation="Disable DTD/external entity resolution in the XML parser.",
         languages=["python", "java", "php", "csharp"]),
    Rule(name="LDAP Injection", cwe="CWE-90", severity="HIGH",
         description="Unsanitized input flows into an LDAP search filter.",
         remediation="Escape LDAP metacharacters and use parameterized search APIs.",
         languages=["python", "java", "php", "csharp"]),
    Rule(name="Insecure JWT", cwe="CWE-347", severity="HIGH",
         description="JWT with 'none' algorithm or disabled signature verification.",
         remediation="Require a strong signing algorithm and verify signatures explicitly.",
         languages=["python", "javascript", "typescript", "go", "java"]),
    Rule(name="Insecure Randomness", cwe="CWE-330", severity="MEDIUM",
         description="Non-cryptographic random used for security-sensitive value.",
         remediation="Use a CSPRNG (secrets module, crypto.randomBytes, SecureRandom).",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go"]),
    Rule(name="Open Redirect", cwe="CWE-601", severity="MEDIUM",
         description="Redirect target derived from user input without validation.",
         remediation="Validate redirect URLs against an allow-list; reject absolute/opaque URLs.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go"]),
    Rule(name="Log Injection", cwe="CWE-117", severity="MEDIUM",
         description="Unsanitized user input written to logs (log forging).",
         remediation="Sanitize/disallow newlines in logged values.",
         languages=["python", "javascript", "typescript", "php", "ruby", "java", "go"]),
    Rule(name="Insecure YAML Deserialization", cwe="CWE-502", severity="CRITICAL",
         description="Unsafe YAML load of untrusted data.",
         remediation="Use a safe loader (yaml.safe_load) or a JSON-based format.",
         languages=["python", "ruby", "go", "java"]),
]
